import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Injectable } from '@angular/core';
import { Episode } from 'src/app/types/episode';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const episodes = [
      {
        "id": 65,
        "name": "A Very Crappy Christmas",
        "season": 4,
        "episode": 17,
        "air_date": "2000-12-20",
        "wiki_url": "https://southpark.fandom.com/wiki/A_Very_Crappy_Christmas",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/7/78/S4E16-Thumbnail.png",
        "description": "When Mr. Hankey skips Christmas, the boys find him living with his alcoholic wife and their three little nuggets. He tells them that no one is into Christmas anymore.\n",
        "created_at": "2022-03-10T17:03:42.000000Z",
        "updated_at": "2022-03-10T17:03:42.000000Z",
      },
      {
        "id": 66,
        "name": "It Hits the Fan",
        "season": 5,
        "episode": 1,
        "air_date": "2001-06-20",
        "wiki_url": "https://southpark.fandom.com/wiki/It_Hits_the_Fan",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/9/92/S5E1-Thumbnail.png",
        "description": "The boys and Chef must stop the world from chanting the curse word \"shit\" because when spoken it causes people to \"puke their own guts out\".\n",
        "created_at": "2022-03-10T17:03:43.000000Z",
        "updated_at": "2022-03-10T17:03:43.000000Z",
      },
      {
        "id": 67,
        "name": "Cripple Fight",
        "season": 5,
        "episode": 2,
        "air_date": "2001-06-27",
        "wiki_url": "https://southpark.fandom.com/wiki/Cripple_Fight",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/e/e2/S5E2-Thumbnail.png",
        "description": "Big Gay Al becomes the boys' scoutmaster and a fight ensues between two handicapped children, Jimmy Swanson and Timmy.\n",
        "created_at": "2022-03-10T17:03:44.000000Z",
        "updated_at": "2022-03-10T17:03:44.000000Z",
      },
      {
        "id": 68,
        "name": "Super Best Friends",
        "season": 5,
        "episode": 3,
        "air_date": "2001-07-04",
        "wiki_url": "https://southpark.fandom.com/wiki/Super_Best_Friends",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/3/3e/Super_Best_Friends_HD.png",
        "description": "A cult comes to South Park and it is up to Stan, Jesus and his super hero comrades to save the world.\n",
        "created_at": "2022-03-10T17:03:44.000000Z",
        "updated_at": "2022-03-10T17:03:44.000000Z",
      },
      {
        "id": 69,
        "name": "Scott Tenorman Must Die",
        "season": 5,
        "episode": 4,
        "air_date": "2001-07-11",
        "wiki_url": "https://southpark.fandom.com/wiki/Scott_Tenorman_Must_Die",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/4/41/S5E4-Thumbnail.png",
        "description": "Cartman repeatedly tries to take revenge on an 8th/9th grader who keeps making fun of him.\n",
        "created_at": "2022-03-10T17:03:44.000000Z",
        "updated_at": "2022-03-10T17:03:44.000000Z",
      },
      {
        "id": 70,
        "name": "Terrance and Phillip: Behind the Blow",
        "season": 5,
        "episode": 5,
        "air_date": "2001-07-18",
        "wiki_url": "https://southpark.fandom.com/wiki/Terrance_and_Phillip:_Behind_the_Blow",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/5/53/BehindtheBlow17.jpg",
        "description": "The boys try to reunite Terrance and Phillip who are feuding so they can perform at an Earth Day assembly.\n",
        "created_at": "2022-03-10T17:03:45.000000Z",
        "updated_at": "2022-03-10T17:03:45.000000Z",
      },
      {
        "id": 71,
        "name": "Cartmanland",
        "season": 5,
        "episode": 6,
        "air_date": "2001-07-25",
        "wiki_url": "https://southpark.fandom.com/wiki/Cartmanland",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/2/21/S5E6-Thumbnail.png",
        "description": "Kyle develops a deadly hemorrhoid and begins to lose his faith in God when Cartman inherits $1 million from his grandmother, which he uses to buy his own amusement park.\n",
        "created_at": "2022-03-10T17:03:45.000000Z",
        "updated_at": "2022-03-10T17:03:45.000000Z",
      },
      {
        "id": 72,
        "name": "Proper Condom Use",
        "season": 5,
        "episode": 7,
        "air_date": "2001-08-01",
        "wiki_url": "https://southpark.fandom.com/wiki/Proper_Condom_Use",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/f/fe/S5E7-Thumbnail.png",
        "description": "The school is forced to teach sex education to the students at a younger age after the boys are found \"milking\" dogs.\n",
        "created_at": "2022-03-10T17:03:45.000000Z",
        "updated_at": "2022-03-10T17:03:45.000000Z",
      },
      {
        "id": 73,
        "name": "Towelie",
        "season": 5,
        "episode": 8,
        "air_date": "2001-08-08",
        "wiki_url": "https://southpark.fandom.com/wiki/Towelie",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/b/b8/S5E8-Thumbnail.png",
        "description": "In order to get their video game console back, the boys must bring a talking towel to the government.\n",
        "created_at": "2022-03-10T17:03:46.000000Z",
        "updated_at": "2022-03-10T17:03:46.000000Z",
      },
      {
        "id": 74,
        "name": "Osama bin Laden Has Farty Pants",
        "season": 5,
        "episode": 9,
        "air_date": "2001-11-07",
        "wiki_url": "https://southpark.fandom.com/wiki/Osama_bin_Laden_Has_Farty_Pants",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/c/cf/S5E9-Thumbnail.png",
        "description": "The boys go to Afghanistan to return a goat given as a gift.\n",
        "created_at": "2022-03-10T17:03:46.000000Z",
        "updated_at": "2022-03-10T17:03:46.000000Z",
      },
      {
        "id": 75,
        "name": "How to Eat with Your Butt",
        "season": 5,
        "episode": 10,
        "air_date": "2001-11-14",
        "wiki_url": "https://southpark.fandom.com/wiki/How_to_Eat_with_Your_Butt",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/f/fd/S5E10-Thumbnail.png",
        "description": "Cartman puts Kenny's picture on a milk carton which brings a family from another state looking for him.\n",
        "created_at": "2022-03-10T17:03:46.000000Z",
        "updated_at": "2022-03-10T17:03:46.000000Z",
      },
      {
        "id": 76,
        "name": "The Entity",
        "season": 5,
        "episode": 11,
        "air_date": "2001-11-21",
        "wiki_url": "https://southpark.fandom.com/wiki/The_Entity",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/b/bd/S5E11-Thumbnail.png",
        "description": "Kyle's cousin, who is also named Kyle, comes to stay in South Park.;Mr. Garrison, tired of the airlines, decides to invent his own vehicle.\n",
        "created_at": "2022-03-10T17:03:46.000000Z",
        "updated_at": "2022-03-10T17:03:46.000000Z",
      },
      {
        "id": 77,
        "name": "Here Comes the Neighborhood",
        "season": 5,
        "episode": 12,
        "air_date": "2001-11-28",
        "wiki_url": "https://southpark.fandom.com/wiki/Here_Comes_the_Neighborhood",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/5/52/S5E12-Thumbnail.png",
        "description": "Token is tired of being teased for being rich, and he brings wealthier families to South Park.\n",
        "created_at": "2022-03-10T17:03:47.000000Z",
        "updated_at": "2022-03-10T17:03:47.000000Z",
      },
      {
        "id": 78,
        "name": "Kenny Dies",
        "season": 5,
        "episode": 13,
        "air_date": "2001-12-05",
        "wiki_url": "https://southpark.fandom.com/wiki/Kenny_Dies",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/5/5a/S5E13-Thumbnail.png",
        "description": "Kenny succumbs to an illness; Cartman acquires stem cells for research.\n",
        "created_at": "2022-03-10T17:03:47.000000Z",
        "updated_at": "2022-03-10T17:03:47.000000Z",
      },
      {
        "id": 79,
        "name": "Butters' Very Own Episode",
        "season": 5,
        "episode": 14,
        "air_date": "2001-12-12",
        "wiki_url": "https://southpark.fandom.com/wiki/Butters%27_Very_Own_Episode",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/7/7e/S5E14-Thumbnail.png",
        "description": "Butters goes on a chase to find out what his father bought his mother for their anniversary.\n",
        "created_at": "2022-03-10T17:03:47.000000Z",
        "updated_at": "2022-03-10T17:03:47.000000Z",
      },
      {
        "id": 80,
        "name": "Jared Has Aides",
        "season": 6,
        "episode": 1,
        "air_date": "2002-03-06",
        "wiki_url": "https://southpark.fandom.com/wiki/Jared_Has_Aides",
        "thumbnail_url": "https://static.wikia.nocookie.net/southpark/images/b/b3/S6E1-Thumbnail2-Jared.png",
        "description": "After meeting Jared Fogle, famous for losing weight by eating Subway sandwiches, the boys form a get-rich-quick scheme involving Butters becoming the weight-loss spokesman for City Wok.\n",
        "created_at": "2022-03-10T17:03:47.000000Z",
        "updated_at": "2022-03-10T17:03:47.000000Z",
      }
    ]
    return {episodes};
  }

  genId(episodes: Episode[]): number {
    return episodes.length > 0 ? Math.max(...episodes.map(episode => episode.id)) + 1 : 11;
  }
}
